language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

    - extra-android-support
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
    - '-.+'

script:
  - ./gradlew build

deploy:
  provider: releases
  file: /build/outputs/apk/release/2048-android-release-unsigned.apk
  skip_cleanup: true
  on:
    repo: Lordpas3/2048-pipeline
    tags: false
    jdk: oraclejdk8
#  api_key:
#    secure: here goes the encrypted api key
