language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

    - extra-android-support
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
    - '-.+'

script:
  - ./gradlew build

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Lordpas3"
  - git config --local user.email "Lordpas3@gmail.com"
  - export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"


deploy:
  provider: releases
  api_key: $SECRET_KEY
  file: "/home/travis/build/outputs/apk/release/2048-android-release-unsigned.apk"
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: Releases
    repo: Lordpas3/2048-pipeline-cin
    tags: false
    jdk: oraclejdk8

