language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

    - extra-android-support
    - extra-android-m2repository

  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
    - '-.+'

script:
  - ./gradlew build

deploy:
  provider: releases
  api_key: $SECRET_KEY
  file: 2048-android/build/outputs/apk/release/2048-android-release-unsigned.apk
  skip_cleanup: true
  on:
    branch: Releases
    repo: Lordpas3/2048-pipeline-cin
    tags: false
    jdk: oraclejdk8

